default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  template: template0

development:
  <<: *default
  database: db/development.postgresql

test:
  <<: *default
  database: db/test.postgresql

production:
  <<: *default
  adapter: postgresql
  database: db/production.postgresql